theme = "lynx"
title = "Botler"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Botler"
  headline = "All the bots you need."
  image = "logo.jpg"
  links = [
    { link = { href = "https://v1.botler.net/blogs", text = "Blog", icon = "link-stack-exchange" } },
    { github = "https://git.botler.net" },
    { x = "https://x.com/username" },
    { telegram = "https://t.me/username" },
    { discord = "https://discord.gg/invitecode" },
    { email = "mailto:hello@your_domain.com" },
    { mastodon = "https://mastodon.instance/@username" },

  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
